on: [push]

jobs:
  creating_ami:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: 'Checkout'
      uses: eduardofesilva/packer-jenkins-slave@master
    - name: Hello world action step
      id: packer
      run: docker docker run -ti -v "$PWD":/go/code --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --env INPUT_PACKERFILE=/go/code/$PACKERFILE --env INPUT_PLAYBOOKFILE=/go/code/$PLAYBOOK packeransible
      env:
        AWS_ACCESS_KEY_ID: {{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: {{ AWS_SECRET_ACCESS_KEY }}
        PACKERFILE: jenkins-slave.json
        PLAYBOOK: jenkins-slave.yml
